#!/usr/bin/env node

/**
 * 🧪 COMPREHENSIVE LOCAL PACKAGE TESTS
 * Generated by build-test-all.js
 */

console.log('🚀 Testing All Local Packages\n');

let allPassed = true;
const results = [];


// Test @axonstream/core
console.log('🧪 Testing @axonstream/core...');
try {
    
    const { AxonPulsClient } = await import('@axonstream/core');
    if (typeof AxonPulsClient === 'undefined') {
        throw new Error('AxonPulsClient is undefined');
    }
    console.log('  ✅ AxonPulsClient: ' + typeof AxonPulsClient);
    const { createAxonStream } = await import('@axonstream/core');
    if (typeof createAxonStream === 'undefined') {
        throw new Error('createAxonStream is undefined');
    }
    console.log('  ✅ createAxonStream: ' + typeof createAxonStream);
    
    results.push({ package: '@axonstream/core', status: 'passed' });
    console.log('✅ @axonstream/core - ALL EXPORTS OK\n');
} catch (error) {
    console.log('❌ @axonstream/core - FAILED:', error.message);
    results.push({ package: '@axonstream/core', status: 'failed', error: error.message });
    allPassed = false;
}

// Test @axonstream/react-hooks
console.log('🧪 Testing @axonstream/react-hooks...');
try {
    
    const { useAxonStream } = await import('@axonstream/react-hooks');
    if (typeof useAxonStream === 'undefined') {
        throw new Error('useAxonStream is undefined');
    }
    console.log('  ✅ useAxonStream: ' + typeof useAxonStream);
    const { useChannel } = await import('@axonstream/react-hooks');
    if (typeof useChannel === 'undefined') {
        throw new Error('useChannel is undefined');
    }
    console.log('  ✅ useChannel: ' + typeof useChannel);
    
    results.push({ package: '@axonstream/react-hooks', status: 'passed' });
    console.log('✅ @axonstream/react-hooks - ALL EXPORTS OK\n');
} catch (error) {
    console.log('❌ @axonstream/react-hooks - FAILED:', error.message);
    results.push({ package: '@axonstream/react-hooks', status: 'failed', error: error.message });
    allPassed = false;
}

// Test @axonstream/cli
console.log('🧪 Testing @axonstream/cli...');
try {
    
    const { AxonStreamCLI } = await import('@axonstream/cli');
    if (typeof AxonStreamCLI === 'undefined') {
        throw new Error('AxonStreamCLI is undefined');
    }
    console.log('  ✅ AxonStreamCLI: ' + typeof AxonStreamCLI);
    
    results.push({ package: '@axonstream/cli', status: 'passed' });
    console.log('✅ @axonstream/cli - ALL EXPORTS OK\n');
} catch (error) {
    console.log('❌ @axonstream/cli - FAILED:', error.message);
    results.push({ package: '@axonstream/cli', status: 'failed', error: error.message });
    allPassed = false;
}

// Test @axonstream/ui
console.log('🧪 Testing @axonstream/ui...');
try {
    
    const { Button } = await import('@axonstream/ui');
    if (typeof Button === 'undefined') {
        throw new Error('Button is undefined');
    }
    console.log('  ✅ Button: ' + typeof Button);
    const { Card } = await import('@axonstream/ui');
    if (typeof Card === 'undefined') {
        throw new Error('Card is undefined');
    }
    console.log('  ✅ Card: ' + typeof Card);
    
    results.push({ package: '@axonstream/ui', status: 'passed' });
    console.log('✅ @axonstream/ui - ALL EXPORTS OK\n');
} catch (error) {
    console.log('❌ @axonstream/ui - FAILED:', error.message);
    results.push({ package: '@axonstream/ui', status: 'failed', error: error.message });
    allPassed = false;
}


// Summary
console.log('=' .repeat(50));
console.log('📊 PACKAGE TEST RESULTS:');
console.log('=' .repeat(50));

results.forEach(result => {
    const status = result.status === 'passed' ? '✅ PASSED' : '❌ FAILED';
    console.log(`  ${result.package}: ${status}`);
    if (result.error) {
        console.log(`    Error: ${result.error}`);
    }
});

const passedCount = results.filter(r => r.status === 'passed').length;
const totalCount = results.length;
const successRate = ((passedCount / totalCount) * 100).toFixed(1);

console.log('\n' + '='.repeat(50));
if (allPassed) {
    console.log(`🎉 ALL PACKAGES WORKING! (${successRate}%)`);
    console.log('✅ Ready for publishing');
} else {
    console.log(`❌ ${totalCount - passedCount} packages failed (${successRate}% success rate)`);
    console.log('🔧 Fix issues before publishing');
}
console.log('='.repeat(50));

process.exit(allPassed ? 0 : 1);
