# Prometheus configuration for AxonPuls Platform monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'AxonPuls-production'
    region: 'us-east-1'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # AxonPuls API Service
  - job_name: 'AxonPuls-api'
    static_configs:
      - targets: ['AxonPuls-api:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s
    honor_labels: true
    params:
      format: ['prometheus']

  # AxonPuls WebSocket Gateway
  - job_name: 'AxonPuls-gateway'
    static_configs:
      - targets: ['AxonPuls-gateway:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s

  # Redis Monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL Monitoring
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Blackbox Exporter (Health Checks)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://AxonPuls-api:3001/health
        - http://AxonPuls-gateway:3002/health
        - wss://AxonPuls-gateway:3002/websocket
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom AxonPuls Metrics
  - job_name: 'AxonPuls-custom-metrics'
    static_configs:
      - targets: ['AxonPuls-api:3001']
    metrics_path: '/api/v1/metrics/custom'
    scrape_interval: 30s
    honor_labels: true
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'AxonPuls_.*'
        target_label: service
        replacement: 'AxonPuls-platform'

  # Container Metrics (if using Docker)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

# Remote write for long-term storage (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.com/api/v1/write"
#     headers:
#       Authorization: "Bearer <token>"

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true
